### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by lfs119** [BLEACH366/P2DFlow#1]
Hi, Thanks for your awesome work.
there maybe have a key_error  when running cal_repr.py and locate in data.utils.py line221

4v23_A_R1_1.pkl

![image](https://github.com/user-attachments/assets/83699f29-58d5-498d-bedb-f4e2558a9c2e)

**Comment by BLEACH366** [comment]
Hi, Thank you for you reply.
I have tried `./data/process_pdb_files.py` and `./data/cal_repr.py` again and the problem doesn't come out.
You can see that we use `parsers.process_chain` in line 81 of `./data/process_pdb_files.py`, and the key `atom_mask` is calculated there. So you can check the running process of `./data/process_pdb_files.py`, and then you may solve it.
